services:
   - type: web
    name: django-hello-world
    env: python
    buildCommand: pip install -r requirements.txt && python myproject/manage.py collectstatic --noinput
    startCommand: gunicorn --chdir myproject myproject.wsgi
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
 